name: Generate Binaries For Release

on:
  release:
    types: 
        - created

jobs:
  build_binaries:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "undeuxpass"
