name: Build And Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: build
        run: make build
      - name: get version from release.json
        uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: 'release.json'
          prop_path: 'version'
      - name: release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.prop }}
          tag_name: ${{ steps.version.outputs.prop }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/linux/undeux
          asset_name: undeux
          asset_content_type: application/octet-stream
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/windows/undeux.exe
          asset_name: undeux.exe
          asset_content_type: application/octet-stream

