name: Build And Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      uses: wangyoucao577/go-release-action@v1.28
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "undeuxpass"
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - bin/linux/undeux
        - bin/windows/undeux.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
